apiVersion: v1
appVersion: "1.10.2"
description: A Helm chart for kured
name: kured
version: 4.0.0
home: https://github.com/kubereboot/kured
maintainers:
  - name: ckotzbauer
    email: christian.kotzbauer@gmail.com
  - name: davidkarlsen
    email: david@davidkarlsen.com
sources:
  - https://github.com/kubereboot/kured
icon: https://raw.githubusercontent.com/kubereboot/kured/main/img/logo.png
