apiVersion: v1
appVersion: "1.20.0"
description: A Helm chart for kured
name: kured
version: 5.11.0
home: https://github.com/kubereboot/kured
maintainers:
  - name: chopf
    email: christian.kotzbauer@gmail.com
  - name: davidkarlsen
    email: david@davidkarlsen.com
sources:
  - https://github.com/kubereboot/kured
icon: https://raw.githubusercontent.com/kubereboot/website/main/static/img/kured.png
